import type { Metadata } from "next";
import "../sass/global.scss";
import RootLayout from "@/components/RootLayout"; // Import Client Component
import localFont from '@next/font/local'
import DeviceRestrictionModal from "@/components/DeviceRestrictionModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

const azonix = localFont({
  src: [{
    path : '../assets/fonts/azonix/Azonix.otf',
  }]
})

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayout><DeviceRestrictionModal />{children}</RootLayout>;
}


// import type { Metadata } from "next";
// import '../sass/global.scss';
// import { Fonts } from "@/lib/fonts";

// import localFont from '@next/font/local'

// import { Toaster } from "sonner";
// import GridContainer from "@/components/GridContainer/GridContainer";

// const azonix = localFont({
//   src: [{
//     path : '../assets/fonts/azonix/Azonix.otf',
//   }]
// })


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   manifest: "/manifest.json",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//             <GridContainer>
//                 {children}
//             </GridContainer>
//             <Toaster position="top-right" richColors duration={1200}/>
//             {/* <PermissionPopupWrapper /> */}

//       </body>
//     </html>
//   );
// }